[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true


[programs.localnet]
multiple = "9bik7qGJDvUMDwzFHGm1GtYydaDpLsCsv5vHGephUcX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
